env:
  browser: true
  es6: true
  jquery: true
extends: 'eslint:recommended'
rules:
  linebreak-style:
    - error
    - unix
  semi: error
  no-caller: error
  no-console:
    - error
    - allow: [info, warn, error]
  no-eq-null: error
  no-implied-eval: error
  no-prototype-builtins: off
  no-self-compare: error
  require-atomic-updates: error
  keyword-spacing:
    - error
    - before: true
      after: true
  space-before-function-paren:
    - error
    - anonymous: always
      named: never
      asyncArrow: always
  space-infix-ops: error
  comma-spacing: error
  brace-style: error
  curly: error
  no-multiple-empty-lines:
    - error
    - max: 1
  operator-linebreak:
    - error
    - before
    - overrides:
        +: ignore
  block-spacing: error
  comma-style: error
  dot-location:
    - error
    - property
  eol-last: error
  func-call-spacing: error
  key-spacing:
    - error
    - mode: minimum
  new-cap:
    - error
    - capIsNew: false
  no-array-constructor: error
  no-duplicate-imports: error
  no-extra-bind: error
  no-extra-parens: error
  no-label-var: error
  no-lone-blocks: error
  no-new-func: error
  no-new-object: error
  no-octal-escape: error
  no-proto: error
  no-return-assign: error
  no-sequences: error
  no-trailing-spaces: error
  no-unmodified-loop-condition: error
  no-unneeded-ternary: error
  no-useless-call: error
  no-useless-computed-key: error
  no-useless-constructor: error
  no-useless-rename: error
  no-whitespace-before-property: error
  object-property-newline: error
  padded-blocks:
    - error
    - never
  rest-spread-spacing: error
  semi-spacing: error
  space-before-blocks: error
  space-in-parens: error
  space-unary-ops: error
  template-curly-spacing: error
  yield-star-spacing:
    - error
    - before: true
      after: true