extends: 'stylelint-config-standard'
rules:
  indentation: 4
  function-name-case:
    - lower
    - ignoreFunctions:
        - '/^DXImageTransform\./'
  color-function-notation: legacy
  color-hex-length: null
  no-descending-specificity: null
  number-leading-zero: null
  block-no-empty: null